from __future__ import annotations

import hashlib
import html
from pathlib import Path
from typing import Any

from ..models import NodeDefinition
from ..storage import write_json


PALETTE = ("#2563EB", "#0F766E", "#7C3AED", "#B45309", "#BE123C", "#0369A1")
TEMPLATE_BY_KIND = {
    "task": "practice",
    "data_skill": "practice",
    "method": "method",
    "knowledge": "knowledge",
    "standard": "standard",
    "practice": "practice",
    "technology": "technology",
    "library": "technology",
    "framework": "technology",
    "infrastructure": "technology",
    "mlops": "technology",
    "database": "technology",
    "data_platform": "technology",
    "tool": "technology",
}


def build_assets(
    root: Path,
    nodes: list[NodeDefinition],
    used_names: set[str],
    contexts: dict[str, list[dict[str, Any]]] | None = None,
) -> dict[str, Any]:
    image_dir = root / "images"
    license_dir = root / "licenses"
    license_dir.mkdir(parents=True, exist_ok=True)
    (license_dir / "PROJECT-TEMPLATE-LICENSE.txt").write_text(
        "SVG files are generated by this project from original geometric templates. "
        "No external icon library or third-party logo is embedded.\n",
        encoding="utf-8",
    )
    node_map = {node.name: node for node in nodes}
    dictionary: dict[str, Any] = {
        "metadata": {
            "format": "SVG",
            "dimensions": "800x480",
            "generator": "graph_service.assets.svg_builder/0.2",
            "status": "PROJECT_GENERATED_TEMPLATES",
            "templates": sorted(set(TEMPLATE_BY_KIND.values())),
            "unique_nodes": len(used_names),
            "image_files": len(used_names),
        },
        "nodes": {},
    }
    for name in sorted(used_names):
        digest = hashlib.sha256(name.encode("utf-8")).hexdigest()
        relative = Path("images") / digest[:2] / f"{digest}.svg"
        target = root / relative
        target.parent.mkdir(parents=True, exist_ok=True)
        color = PALETTE[int(digest[:2], 16) % len(PALETTE)]
        node = node_map[name]
        template_id = TEMPLATE_BY_KIND.get(node.kind, "technology")
        target.write_text(_svg(name, color, template_id), encoding="utf-8")
        dictionary["nodes"][name] = {
            "id": digest,
            "image": relative.as_posix(),
            "base_node": name,
            "kind": node.kind,
            "template_id": template_id,
            "source": "project-generated geometric template",
            "license": "PROJECT-TEMPLATE-LICENSE",
            "contexts": (contexts or {}).get(name, []),
        }
    write_json(root / "image_dictionary.json", dictionary)
    return dictionary


def _svg(name: str, color: str, template_id: str) -> str:
    label = html.escape(name)
    initials = html.escape("".join(word[0].upper() for word in name.split()[:3]) or "N")
    symbol = _symbol(template_id, color, initials)
    font_size = max(24, min(38, 760 // max(len(name), 1)))
    return f'''<svg xmlns="http://www.w3.org/2000/svg" width="800" height="480" viewBox="0 0 800 480" role="img" aria-label="{label}">
  <rect width="800" height="480" rx="48" fill="#F8FAFC"/>
  {symbol}
  <text x="400" y="374" text-anchor="middle" font-family="Arial, sans-serif" font-size="{font_size}" font-weight="600" fill="#0F172A">{label}</text>
  <text x="400" y="420" text-anchor="middle" font-family="Arial, sans-serif" font-size="18" fill="#64748B">{template_id}</text>
</svg>
'''


def _symbol(template_id: str, color: str, initials: str) -> str:
    if template_id == "method":
        return f'''<path d="M300 270 L400 88 L500 270 Z" fill="{color}"/>
  <circle cx="400" cy="196" r="42" fill="#FFFFFF"/>
  <text x="400" y="213" text-anchor="middle" font-family="Arial, sans-serif" font-size="42" font-weight="700" fill="{color}">{initials}</text>'''
    if template_id == "knowledge":
        return f'''<path d="M280 115 Q340 85 400 125 Q460 85 520 115 V290 Q460 265 400 305 Q340 265 280 290 Z" fill="{color}"/>
  <path d="M400 126 V304" stroke="#FFFFFF" stroke-width="8"/>
  <text x="400" y="225" text-anchor="middle" font-family="Arial, sans-serif" font-size="44" font-weight="700" fill="#FFFFFF">{initials}</text>'''
    if template_id == "practice":
        return f'''<rect x="292" y="92" width="216" height="216" rx="34" fill="{color}"/>
  <path d="M340 160 L375 195 L455 125 M340 235 L375 270 L455 200" fill="none" stroke="#FFFFFF" stroke-width="16" stroke-linecap="round" stroke-linejoin="round"/>
  <text x="470" y="292" text-anchor="middle" font-family="Arial, sans-serif" font-size="28" font-weight="700" fill="#FFFFFF">{initials}</text>'''
    if template_id == "standard":
        return f'''<path d="M400 78 L510 120 V205 C510 270 465 315 400 335 C335 315 290 270 290 205 V120 Z" fill="{color}"/>
  <text x="400" y="228" text-anchor="middle" font-family="Arial, sans-serif" font-size="62" font-weight="700" fill="#FFFFFF">{initials}</text>'''
    return f'''<path d="M400 76 L500 132 V246 L400 302 L300 246 V132 Z" fill="{color}"/>
  <circle cx="400" cy="189" r="70" fill="#FFFFFF" opacity="0.18"/>
  <text x="400" y="216" text-anchor="middle" font-family="Arial, sans-serif" font-size="68" font-weight="700" fill="#FFFFFF">{initials}</text>'''
